#! /usr/bin/env lua

local M = {}

local handle = io.popen(
  "grim -g \"$(slurp -b '#00000000' -p)\" -t ppm - | "
  .. "magick - -format '%[pixel:p{0,0}]' txt:- | "
  .. "awk 'END{print $3}'"
)
local color = handle:read("*l")
handle:close()

local S = dofile(os.getenv("HOME") .. "/.aquamoon/settings.lua")
local notify = dofile(S.path .. "/scripts/sys/notify.lua")

if not color or color == "" then
  notify.send("No color selected.")
  os.exit(1)
end

local clip = io.popen("wl-copy", "w")
clip:write(color)
clip:close()

notify.send("Color: " .. color)

return M
