[Kensington_Eagle_Trackball]
device = "pointer-1149-8264-Kensington_Eagle_Trackball"
pointer-accel = 4

[PIXA200B_Touchpad]
device = "pointer-2362-8203-PIXA200B:00_093A:200B_Touchpad"
pointer-accel = 0.75
tap = "enabled"

[Microsoft_Mouse]
device = "pointer-1118-64-Microsoft_Microsoft_3-Button_Mouse_with_IntelliEye\\(TM\\)"
pointer-accel = 3
