[path]
home = "~/.aquamoon"

# combine multiple neovim themes into one aquamoon theme?
# TODO try carvion, poimandres and oldworld
[theme_list]
OrangeLight = "carvion"

GrayLight = "noirblaze"
GrayDark = "sweetie"

GlowLight = "mfd-paper"
GlowDark = "bluloco"

VoidLight = "paramount"
VoidDark = "moonfly"

[river_options]
border-width = 2
set-repeat = [50, 300]
focus-follows-cursor = "normal"
attach-mode = "right"
default-layout = "luatile"
output-layout = "luatile"

[window_rules.ssd]
0 = "firefox"
1 = "gimp"
2 = "neovide"
3 = "steam"
4 = "com.system76.CosmicFiles"
5 = "mpv"
6 = "imv"
7 = "qutebrowser"
8 = "glide-glide"

[write_configs]
dunstrc = "~/.config/dunst/dunstrc"
television = "~/.config/television/config.toml"
lazygit = "~/.config/lazygit/config.yml"
