[path]
home = "~/.aquamoon"

[theme_list]
Grey = "sweetie"
Purple = "moonfly"
Purple2 = "yorumi"
Blue = "bluloco"
Olive = "mfd"
Green = "mfd-hud"
Amber = "mfd-amber"
GB = "mfd-gbl-light"
Orange = "afterglow"
Pink = "noirblaze"
Monokai = "monokai-nightasty"

[river_options]
border-width = 2
set-repeat = [50, 300]
focus-follows-cursor = "normal"
attach-mode = "right"
default-layout = "luatile"
output-layout = "luatile"

[nvim]
godot_executable = "/bin/godot3"
flag = "󰈿"

[nvim.lazygit]
scaling_factor = 1
border_chars = ["", "", "", "", "", "", "", ""]

[nvim.diagnostics]
signs = false
virtual_lines = true
enable = false

[nvim.leader]
key = ","
mapleader = ","
maplocalleader = ","

[nvim.plugins.hipatterns]
WARN = "%f[%w]()WARN()%f[%W]"
HACK = "%f[%w]()HACK()%f[%W]"
TODO = "%f[%w]()TODO()%f[%W]"

[nvim.plugins.starter]
recent_files_count = 20
padding = [0, 5]

[nvim.plugins.unconfigured_mini]
0 = "ai"
1 = "align"
2 = "basics"
3 = "bracketed"
4 = "comment"
5 = "diff"
6 = "icons"
7 = "jump"
8 = "keymap"
9 = "move"
10 = "pairs"
11 = "sessions"
12 = "surround"
13 = "trailspace"
14 = "visits"

[nvim.plugins.tv.channels]
files = { keybinding = "<leader>f" }
text = { keybinding = "<leader>g" }

[nvim.plugins.snipe]
position = "center"
text_align = "file-first"
navigate = { open_vsplit = "e", open_split = "E" }

[nvim.plugins.cling.wrappers]
1 = { command = "Lg", binary = "lazygit", close_on_exit = true }
2 = { command = "Serve", binary = "simple-http-server", close_on_exit = true }
3 = { command = "Theme", binary = "lua ~/.aquamoon/scripts/theme_picker.lua" }
4 = { command = "Deploy", binary = "lua ./deploy.lua" }
5 = { command = "Far", binary = "scooter", close_on_exit = true }
6 = { command = "AI", binary = "opencode", close_on_exit = true }
7 = { command = "DDGR", binary = "ddgr", close_on_exit = true }

[window_rules.ssd]
0 = "firefox"
1 = "gimp"
2 = "neovide"
3 = "steam"
4 = "com.system76.CosmicFiles"
5 = "mpv"
6 = "imv"
7 = "qutebrowser"
8 = "glide-glide"

[write_configs]
dunstrc = "~/.config/dunst/dunstrc"
television = "~/.config/television/config.toml"
lazygit = "~/.config/lazygit/config.yml"
