0 = ["dbus-update-activation-environment", "DISPLAY", "WAYLAND_DISPLAY", "XDG_SESSION_TYPE", "XDG_CURRENT_DESKTOP"]
1 = ["swayidle", "timeout", "1800", "gtklock"]
2 = ["dunst"]
3 = ["clapboard --record"]
4 = ["lua ~/.aquamoon/scripts/daemon/low_battery_warning.lua"]
5 = ["river-luatile"]
