# MFD GBL LIGHT https://github.com/cursorinsight/mfd.nvim
[mfd_gbl_light]
text_primary = "004F3A"
text_secondary = "009A70"
background = "02B582"
background_alt = "01A878"
accent = "01694A"
background_image = "~/.aquamoon/wallpapers/aurora.jpg"
border_width = 3
opacity = 1.0
ddgr_colors = "cegceg"

[mfd_gbl_light.active_font]
name = "BigBlueTermPlus Nerd Font Propo:h14"
path = "'/usr/share/fonts/TTF/BigBlueTermPlusNerdFontPropo-Regular.ttf'"
size = 14

# MOONFLY https://github.com/bluz71/vim-moonfly-colors
[moonfly]
text_primary = "ae81ff"
text_secondary = "bdbdbd"
background = "080808"
background_alt = "ae81ff"
accent = "cf87e8"
background_image = "~/.aquamoon/wallpapers/aurora.jpg"
border_width = 4
opacity = 0.8
ddgr_colors = "hcegch"

[moonfly.active_font]
name = "BigBlueTermPlus Nerd Font Propo:h14"
path = "'/usr/share/fonts/TTF/BigBlueTermPlusNerdFontPropo-Regular.ttf'"
size = 14

# SWEETIE https://github.com/NTBBloodbath/sweetie.nvim
[sweetie]
text_primary = "92d3c5"
text_secondary = "d3d7de"
background = "2a2a3a"
background_alt = "92d3c5"
accent = "b094e2"
background_image = "~/.aquamoon/wallpapers/macos_tiger_grey.png"
border_width = 2
opacity = 0.66
ddgr_colors = "gcedge"

[sweetie.active_font]
name = "Lilex Nerd Font:14"
path = "'/usr/share/fonts/TTF/LilexNerdFont-Regular.ttf'"
size = 14

# BLULOCO https://github.com/uloco/bluloco.nvim
[bluloco]
text_primary = "10b0fe"
# text_primary = "abb2bf"
text_secondary = "cdd3e0"
background = "282c34"
background_alt = "10b0fe"
accent = "3691ff"
background_image = "~/.aquamoon/wallpapers/glowtime_light.jpg"
border_width = 2
opacity = 0.8
ddgr_colors = "gedegd"

[bluloco.active_font]
name = "Agave Nerd Font:h14"
path = "'/usr/share/fonts/TTF/AgaveNerdFont-Regular.ttf'"
size = 14

# MFD https://github.com/cursorinsight/mfd.nvim
[mfd]
text_primary = "1e2d1e"
text_secondary = "5a6b49"
background = "7a8b69"
background_alt = "0d1d0d"
accent = "0d1d0d"
background_image = "~/.aquamoon/wallpapers/puma.png"
border_width = 3
opacity = 1.0
ddgr_colors = "cegceg"

[mfd.active_font]
name = "Ioskeley Mono Semibold:style=Semibold,Regular:h14"
path = "'/usr/share/fonts/ttf/ttf-ioskeley-mono-unhinted/IoskeleyMono-SemiBold.ttf'"
size = 14

# MFD AMBER https://github.com/cursorinsight/mfd.nvim
[mfd_amber]
text_primary = "cc9944"
text_secondary = "382818"
background = "0f0c08"
background_alt = "ffbb55"
accent = "ffbb55"
background_image = "~/.aquamoon/wallpapers/aurora.jpg"
border_width = 3
opacity = 1.0
ddgr_colors = "hchchc"

[mfd_amber.active_font]
name = "Ioskeley Mono Semibold:style=Semibold,Regular:h14"
path = "'/usr/share/fonts/ttf/ttf-ioskeley-mono-unhinted/IoskeleyMono-SemiBold.ttf'"
size = 14

# MFD HUD
[mfd_hud]
text_primary = "60a060"
text_secondary = "2a4a2a"
background = "0a140a"
background_alt = "80c080"
accent = "80c080"
background_image = "~/.aquamoon/wallpapers/puma.png"
border_width = 3
opacity = 1.0
ddgr_colors = "cegceg"

[mfd_hud.active_font]
name = "BigBlueTermPlus Nerd Font Propo:h14"
path = "'/usr/share/fonts/TTF/BigBlueTermPlusNerdFontPropo-Regular.ttf'"
size = 14


# YORUMI https://github.com/yorukotakee/yorumi.nvim
[yorumi]
text_primary = "c6dfec"
text_secondary = "878996"
background = "060914"
background_alt = "a188c3"
accent = "a188c3"
background_image = "~/.aquamoon/wallpapers/glowtime_dark.jpg"
border_width = 2
opacity = 0.8
ddgr_colors = "chchch"

[yorumi.active_font]
name = "Lilex Nerd Font:14"
path = "'/usr/share/fonts/TTF/LilexNerdFont-Regular.ttf'"
size = 14

# MONOKAI NIGHTASTY https://github.com/andersevenrud/monokai-nightasty.nvim
[monokai_nightasty]
text_primary = "ffffff"
text_secondary = "8a8a8a"
background = "2b2b2b"
background_alt = "fc1a70"
accent = "fc1a70"
background_image = "~/.aquamoon/wallpapers/macos_tiger_grey.png"
border_width = 2
opacity = 0.85
ddgr_colors = "hchchc"

[monokai_nightasty.active_font]
name = "Agave Nerd Font:h14"
path = "'/usr/share/fonts/TTF/AgaveNerdFont-Regular.ttf'"
size = 14

# NOIRBLAZE https://github.com/aquamoon/noirblaze-vim
[noirblaze]
text_primary = "b4b4b4"
text_secondary = "737373"
background = "121212"
background_alt = "ff0088"
accent = "ff0088"
background_image = "~/.aquamoon/wallpapers/glowtime_dark.jpg"
border_width = 2
opacity = 1.0
ddgr_colors = "chchch"

[noirblaze.active_font]
name = "FiraCode Nerd Font:h14"
path = "'/usr/share/fonts/TTF/FiraCodeNerdFont-Regular.ttf'"
size = 14

# AFTERGLOW https://github.com/danilo-augusto/afterglow
[afterglow]
text_primary = "d6d6d6"
text_secondary = "797979"
background = "1a1a1a"
background_alt = "e87d3e"
accent = "e87d3e"
background_image = "~/.aquamoon/wallpapers/aurora.jpg"
border_width = 2
opacity = 1.0
ddgr_colors = "eheheh"

[afterglow.active_font]
name = "FiraCode Nerd Font:h14"
path = "'/usr/share/fonts/TTF/FiraCodeNerdFont-Regular.ttf'"
size = 14


