# MOONFLY https://github.com/bluz71/vim-moonfly-colors
[moonfly]
fg = "ae81ff"
fg2 = "bdbdbd"
bg = "080808"
bg2 = "ae81ff"
accent = "cf87e8"
background_image = "~/.aquamoon/wallpapers/aurora.jpg"
border_width = 4
opacity = 0.8
ddgr_colors = "hcegch"

[moonfly.active_font]
name = "BigBlueTermPlus Nerd Font Propo:h14"
path = "'/usr/share/fonts/TTF/BigBlueTermPlusNerdFontPropo-Regular.ttf'"
size = 14

# SWEETIE https://github.com/NTBBloodbath/sweetie.nvim
[sweetie]
fg = "92d3c5"
fg2 = "d3d7de"
bg = "2a2a3a"
bg2 = "92d3c5"
accent = "b094e2"
background_image = "~/.aquamoon/wallpapers/macos_tiger_grey.png"
border_width = 4
opacity = 0.8
ddgr_colors = "gcedge"

[sweetie.active_font]
name = "Lilex Nerd Font:14"
path = "'/usr/share/fonts/TTF/LilexNerdFont-Regular.ttf'"
size = 14

# BLULOCO https://github.com/uloco/bluloco.nvim
[bluloco]
fg = "10b0fe"
# fg = "abb2bf"
fg2 = "cdd3e0"
bg = "282c34"
bg2 = "10b0fe"
accent = "3691ff"
background_image = "~/.aquamoon/wallpapers/glowtime_light.jpg"
border_width = 2
opacity = 0.8
ddgr_colors = "gedegd"

[bluloco.active_font]
name = "Agave Nerd Font:h14"
path = "'/usr/share/fonts/TTF/AgaveNerdFont-Regular.ttf'"
size = 14

# CHALLENGER DEEP https://github.com/challenger-deep-theme
[challenger_deep]
fg = "cbe3e7"
fg2 = "a6b3cc"
bg = "1b182c"
bg2 = "100e23"
accent = "95ffa4"
background_image = "~/.aquamoon/wallpapers/panther.png"
border_width = 4
opacity = 0.8
ddgr_colors = "gcedge"

[challenger_deep.active_font]
name = "BigBlueTermPlus Nerd Font Propo:h14"
path = "'/usr/share/fonts/TTF/BigBlueTermPlusNerdFontPropo-Regular.ttf'"
size = 14
