#!/usr/bin/env sh

FIFO="$XDG_RUNTIME_DIR/sandbar"
[ -e "$FIFO" ] && rm -f "$FIFO"
mkfifo "$FIFO"

# TODO use a lua script for this so it can change depending on the theme
while cat "$FIFO"; do :; done | sandbar \
-font "BigBlueTermPlus Nerd Font Propo:Pixelsize" \
-bottom \
-no-mode \
-active-fg-color "#47948a" \
-active-bg-color "#798399" \
-inactive-fg-color "#798399" \
-inactive-bg-color "#47948a" \
-urgent-fg-color "#50FA7B" \
-urgent-bg-color "#282A36" \
-title-fg-color "#798399" \
-title-bg-color "#47948a"
# -font "FairiesevkaTerm Nerd Font Mono ExtraBold:Pixelsize" \
# -title-fg-color "#798399" \
