#!/usr/bin/env sh

FIFO="$XDG_RUNTIME_DIR/sandbar"
[ -e "$FIFO" ] && rm -f "$FIFO"
mkfifo "$FIFO"

# TODO use a lua script for this so it can change depending on the theme
while cat "$FIFO"; do :; done | sandbar \
-font "FairiesevkaTerm Nerd Font Mono ExtraBold:Pixelsize" \
-bottom \
-no-mode \
-active-fg-color "#2a2a3a" \
-active-bg-color "#eb6f92" \
-inactive-fg-color "#eb6f92" \
-inactive-bg-color "#2a2a3a" \
-urgent-fg-color "#50FA7B" \
-urgent-bg-color "#282A36" \
-title-fg-color "#eb6f92" \
-title-bg-color "#2a2a3a"
# -active-fg-color "#282A36" \
# -active-bg-color "#50FA7B" \
# -inactive-fg-color "#50FA7B" \
# -inactive-bg-color "#282A36" \
# -urgent-fg-color "#50FA7B" \
# -urgent-bg-color "#282A36" \
# -title-fg-color "#50FA7B" \
# -title-bg-color "#282A36"
# -font "BigBlueTermPlus Nerd Font Propo:Pixelsize" \
