# TODO set up everything in the terminal using nvim/terminal.lua

export LS_COLORS="$(vivid generate catppuccin-frappe)"

# ZSH
export HISTFILE=$HOME/.zsh_history
export BROWSER="glide-bin"
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FIND_NO_DUPS

# SYSTEM
alias q="exit"
alias s="sudo"

# APPLICATIONS
alias buku="buku --suggest"
alias ddgr="ddgr --rev" # TODO open ddgr with a keybind
alias lg="lazygit"
alias rsync="rsync -Phav"
alias v="nvim"
alias open="xdg-open"
alias yank="wl-copy"
alias put="wl-paste"

# SYSTEM INFO
alias ls='eza --icons --group-directories-first'
alias tasks="ps aux"
alias fd="sudo fdisk -l"
alias df="duf"
alias du="dust -X .git"
alias cat="bat"
alias top="htop"

# MOVEMENT
alias ..='cd ../'
alias ...='cd ../../'
alias ....='cd ../../../'
alias cls='clear && ls'
alias l='clear && ls'

# ZSH FUNCTIONS
hist() { peco < $HISTFILE } # search history
chmodx() { sudo chmod u+x $1 }
take() { mkdir $1 && cd $1 }
softclone() { git clone ssh://soft/$(ssh soft repo list | peco) }
serve() { simple-http-server -i --nocache --threads 6 --ip 127.0.0.1 ${1-./} }
rgr() { rg $2 -A $1 -B $1 }
rga() { rg $2 -A $1 }
rgb() { rg $2 -B $1 }
